#!/bin/sh -e

if ! command -v rubocop >/dev/null 2>&1; then
  echo "Rubocop is not installed. Run:"
  echo "$ gem install rubocop"
  exit 1
fi

echo 'Running rubocop...'

if ! rubocop; then
  echo '\033[0;31mLint errors returned. Aborting commit.\033[0m'
  exit 1
fi
