FROM ruby:2.6.3-slim-stretch

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    apt-utils \
    build-essential \
    curl \
    firefox-esr \
    git-core \
    stoken \
    wget \
  && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/wolfcw/libfaketime \
  && cd libfaketime && make && make install

ENV LD_PRELOAD=/usr/local/lib/faketime/libfaketime.so.1

#============
# GeckoDriver
#============
ARG GECKODRIVER_VERSION=0.24.0
RUN wget --no-verbose --no-check-certificate -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz \
  && tar -zxf geckodriver.tar.gz \
  && rm geckodriver.tar.gz \
  && mv geckodriver /usr/bin/geckodriver \
  && chmod 755 /usr/bin/geckodriver

WORKDIR /taf

# Copy enough files in to install all the taf's dependencies.
COPY Gemfile.test taf.gemspec ./
COPY lib/taf/version.rb lib/taf/version.rb

RUN bundle install --gemfile Gemfile.test

CMD ["rspec"]
