#!/usr/bin/env groovy

// Jenkinsfile for the TAF to run in pipeline to run full regression test pack.
node {
    stage('Code Checkout'){
        echo 'Code Checkout'
        git branch:"master", url:"https://github.com/Aperrett/TAF.git"
    }
    stage('Build Test Environment') {
        echo 'Build Docker Test Environment'
        sh "docker build -t taf ./Code/"
        echo 'Finished Building Docker Test Enviroment'
    }
    stage('Run Full Regression Test Pack'){
        echo 'Run Full Regression Test Pack in Docker'
        sh 'docker run --rm -v "$(pwd)"/target:/app/Results:cached taf ruby main.rb Tests/TS_test.csv'
        echo 'Finished Running Tests'
    }
    stage('Clean Workspace'){
        echo 'Clean Workspace'
        cleanWs deleteDirs: true, patterns: [[pattern: 'Code', type: 'INCLUDE'], [pattern: 'Excel_Templates', type: 'INCLUDE'], [pattern: 'target', type: 'EXCLUDE']]
        echo 'Test Result can be found in the Jenkins workspace in the <target> folder'
    }
}
